# Generated by Django 4.2.15 on 2025-09-05 13:03

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=30, unique=True, verbose_name='name'),
        ),
    ]
